In [2]:
# !pip install numpy

In [3]:
import numpy as np

## create array using Numpy
## 1D array

arr = np.array([1,2,3,4,5])
print(arr)
print(arr.shape)
type(arr)

[1 2 3 4 5]
(5,)


numpy.ndarray

In [4]:
arr2 = np.array([1,2,3,4,5,6])
print(arr2.reshape([2,3]))
arr2.reshape([3,2])
# arr2.reshape([3,3])

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
arr3 = np.array([[1,2,3],[5,6,8]])
print(arr3)
print(arr3.shape)

[[1 2 3]
 [5 6 8]]
(2, 3)


In [6]:
## INbuilt Functions
## Arrange

np.arange(1,10,3).reshape(3,1)

array([[1],
       [4],
       [7]])

In [7]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [8]:
np.zeros((3,4)).reshape(2,6)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Attributes of NUMPY

In [10]:
arr = np.array(([1,2,3],[4,5.2,6]))
print("Array: \n", arr)
print("No.of dimension:", arr.ndim)
print("number of elements:",arr.size)
print("Datatype:",arr.dtype)
print("Item size: ",arr.itemsize)

Array: 
 [[1.  2.  3. ]
 [4.  5.2 6. ]]
No.of dimension: 2
number of elements: 6
Datatype: float64
Item size:  8


### Numpy Vectorized Operation

In [11]:
Arr = np.array([1,2,3,4,5,6])
Arr2 = np.array([10,20,30,40,50,60])

## Element wise Addition

print("Addition is: ",Arr+Arr2)

## Element Wise Subtraction

print("Subtraction: ",Arr-Arr2)
print("Subtraction: ",Arr2*Arr)

print(Arr.sum())
print(Arr2.sum())
print("Sum of two arrays are:",Arr.sum()+Arr2.sum())

Addition is:  [11 22 33 44 55 66]
Subtraction:  [ -9 -18 -27 -36 -45 -54]
Subtraction:  [ 10  40  90 160 250 360]
21
210
Sum of two arrays are: 231


### Universal Functions

In [12]:
arr = np.array([25,64,36])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))

[5. 8. 6.]
[7.20048993e+10 6.23514908e+27 4.31123155e+15]
[-0.13235175  0.92002604 -0.99177885]


### Slicing and Indexing

In [13]:
arr = np.array([[1,2,3,4],[5,6,7,8],[10,11,12,13]])
print(arr)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]]


In [14]:
arr[0][0]

np.int64(1)

In [15]:
arr[1:2,0:2]

array([[5, 6]])

In [16]:
arr[1:3,0:2]

array([[ 5,  6],
       [10, 11]])

In [17]:
arr[0:2,1:3]

array([[2, 3],
       [6, 7]])

In [18]:
arr[1:3,1:3] = 100
print(arr)

[[  1   2   3   4]
 [  5 100 100   8]
 [ 10 100 100  13]]


### Normalization
- which has mean 0 and standard deviation 1

In [19]:
data = np.array([70,80,90,100])

mean = np.mean(data)
print(mean)

std = np.std(data)
print(std)

normal_devoiation = (data - mean) / std
print(normal_devoiation)

85.0
11.180339887498949
[-1.34164079 -0.4472136   0.4472136   1.34164079]


In [20]:
data = np.array([10,20,30])
print(data-5)
print(data+5)
print(data/5)
print(data//5)
print(data%5)

[ 5 15 25]
[15 25 35]
[2. 4. 6.]
[2 4 6]
[0 0 0]


In [21]:
arr = np.random.randint(1,100,(3,4))
print(arr)
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("No. of elements:", arr.size)
print("Datatype:", arr.dtype)
print("Itemsize:", arr.itemsize)


[[36 78 58  8]
 [85 14 36 82]
 [76 86 95 23]]
Shape: (3, 4)
Dimensions: 2
No. of elements: 12
Datatype: int32
Itemsize: 4


In [22]:
data2 = np.array([1,2,3,4,5,6,7,8,9])

#mean

mean = np.mean(data2)
print(mean)

mean = np.var(data2)
print(mean)

5.0
6.666666666666667


In [23]:
data3 = np.array([15,5,3,10,45])
data3[(data3>10) & (data3>=15)]

array([15, 45])